export type PillarType = "dekomposisi" | "pola" | "abstraksi" | "algoritma";
export type DifficultyLevel = "pemula" | "menengah" | "mahir";

export interface SimulatorItem {
  id: string;
  pillar: PillarType;
  pillarNumber: number; // 1 to 10
  title: string;
  subtitle: string;
  difficulty: DifficultyLevel;
  difficultyBadge: string;
  storyContext: string;
  studentChallenge: string;
  instruction: string;
  // Specific interactive setup
  gameType: "categorize" | "sequence" | "filter_essential" | "binary_search" | "pattern_detect" | "route_planner" | "dependency_tree";
  items: Array<{
    id: string;
    label: string;
    category?: string;
    isEssential?: boolean;
    isCorrect?: boolean;
    order?: number;
    details?: string;
    icon?: string;
  }>;
  categories?: string[];
  targetSequence?: string[];
  correctAnswers?: string[]; // IDs
  hint: string;
  ctExplanation: string;
  dailyLifeBenefit: string;
}

export const DAILY_LIFE_SIMULATORS: SimulatorItem[] = [
  // ==========================================
  // 1. DEKOMPOSISI (10 SIMULATOR KEHIDUPAN SISWA)
  // ==========================================
  {
    id: "dek-1",
    pillar: "dekomposisi",
    pillarNumber: 1,
    title: "Menyiapkan Tas & Seragam Upacara Senin",
    subtitle: "Pilar Dekomposisi • Memilah perlengkapan penting sebelum terlambat",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Hari Senin pagi ada upacara bendera dan 3 mata pelajaran (Informatika, Matematika, dan Penjas). Jika tas tidak disiapkan dengan rapi sejak malam, kamu berisiko terlambat atau dihukum karena atribut tidak lengkap.",
    studentChallenge: "Kelompokkan perlengkapan siswa ke dalam 3 sub-bagian yang tepat: 'Atribut Upacara', 'Buku & Alat Tulis', dan 'Perlengkapan Tambahan'.",
    instruction: "Klik dan masukkan setiap barang ke dalam kelompok yang sesuai.",
    gameType: "categorize",
    categories: ["Atribut Upacara", "Buku & Alat Tulis", "Perlengkapan Tambahan"],
    items: [
      { id: "d1-1", label: "Topi & Dasi Sekolah", category: "Atribut Upacara", icon: "GraduationCap" },
      { id: "d1-2", label: "Sabuk / Gesper Hitam", category: "Atribut Upacara", icon: "Shield" },
      { id: "d1-3", label: "Buku Tulis & Modul Informatika", category: "Buku & Alat Tulis", icon: "BookOpen" },
      { id: "d1-4", label: "Kotak Pensil & Penggaris", category: "Buku & Alat Tulis", icon: "PenTool" },
      { id: "d1-5", label: "Baju Olahraga Ganti", category: "Perlengkapan Tambahan", icon: "Shirt" },
      { id: "d1-6", label: "Botol Minum / Tumbler", category: "Perlengkapan Tambahan", icon: "Coffee" },
    ],
    hint: "Pikirkan apa saja yang wajib dipakai saat baris di lapangan upacara, apa yang dimasukkan ke tas untuk pelajaran kelas, dan apa yang dipakai siang hari.",
    ctExplanation: "Dekomposisi memecah kekacauan pagi hari menjadi 3 sub-masalah independen. Kamu tidak perlu panik mencari semua barang sekaligus di detik-detik terakhir.",
    dailyLifeBenefit: "Mencegah kelupaan atribut upacara yang berujung poin tata tertib dan membuat pagi hari tenang tanpa tergesa-gesa."
  },
  {
    id: "dek-2",
    pillar: "dekomposisi",
    pillarNumber: 2,
    title: "Membuat Bekal Nasi Goreng Telur Praktis",
    subtitle: "Pilar Dekomposisi • Memisahkan bahan pokok, bumbu dapur, dan peralatan",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Untuk menghemat uang saku, kamu memutuskan membawa bekal sarapan buatan sendiri sebelum berangkat sekolah pukul 06.15.",
    studentChallenge: "Dekompisikan persiapan masak menjadi 3 elemen: 'Bahan Pokok', 'Bumbu Masak', dan 'Alat Memasak'.",
    instruction: "Kelompokkan setiap komponen agar proses memasak berjalan cepat tanpa bolak-balik buka lemari.",
    gameType: "categorize",
    categories: ["Bahan Pokok", "Bumbu Masak", "Alat Memasak"],
    items: [
      { id: "d2-1", label: "Nasi Putih Dingin & Telur", category: "Bahan Pokok" },
      { id: "d2-2", label: "Bawang Merah & Bawang Putih Cincang", category: "Bumbu Masak" },
      { id: "d2-3", label: "Garam, Merica & Kecap Manis", category: "Bumbu Masak" },
      { id: "d2-4", label: "Wajan Penggorengan & Spatula", category: "Alat Memasak" },
      { id: "d2-5", label: "Kompor Gas & Minyak Goreng", category: "Alat Memasak" },
      { id: "d2-6", label: "Irisan Sosis & Daun Bawang", category: "Bahan Pokok" },
    ],
    hint: "Bahan pokok adalah makanan intinya, bumbu adalah perasa, sedangkan alat adalah perkakas kompornya.",
    ctExplanation: "Memasak adalah proses rekayasa sistem. Menyiapkan bahan (mise en place) memisahkan tahap persiapan dari tahap eksekusi penggorengan.",
    dailyLifeBenefit: "Memasak selesai hanya dalam 10 menit tanpa gosong karena semua bahan telah didekomposisi sebelum kompor dinyalakan."
  },
  {
    id: "dek-3",
    pillar: "dekomposisi",
    pillarNumber: 3,
    title: "Merapikan Kamar & Meja Belajar",
    subtitle: "Pilar Dekomposisi • Klasifikasi barang berserakan di kamar tidur",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Kamar tidur dan meja belajarmu sangat berantakan setelah seminggu ujian harian. Kamu ingin membersihkannya dalam 15 menit.",
    studentChallenge: "Pecah proses pembersihan kamar ke dalam wadah: 'Keranjang Cucian', 'Rak Buku/Alat Tulis', dan 'Tempat Sampah Kertas'.",
    instruction: "Klasifikasikan benda-benda berikut ke tempat tujuan yang benar.",
    gameType: "categorize",
    categories: ["Keranjang Cucian", "Rak Buku/Alat Tulis", "Tempat Sampah Kertas"],
    items: [
      { id: "d3-1", label: "Kaos Kaki & Seragam Pramuka Kotor", category: "Keranjang Cucian" },
      { id: "d3-2", label: "Struk Jajan & Bungkus Roti Bekas", category: "Tempat Sampah Kertas" },
      { id: "d3-3", label: "Kertas Coretan Rumus Matematika Kusut", category: "Tempat Sampah Kertas" },
      { id: "d3-4", label: "Buku Paket Biologi & Kamus Bahasa Inggris", category: "Rak Buku/Alat Tulis" },
      { id: "d3-5", label: "Spidol, Binder & Flashdisk", category: "Rak Buku/Alat Tulis" },
      { id: "d3-6", label: "Handuk Mandi Basah di Kasur", category: "Keranjang Cucian" },
    ],
    hint: "Pisahkan mana yang harus dicuci, mana yang harus dibuang, dan mana perlengkapan belajar yang masih dipakai.",
    ctExplanation: "Melihat kamar berantakan tampak melelahkan, tetapi dengan dekomposisi per zona wadah, tugas berat berubah menjadi beberapa aksi sederhana.",
    dailyLifeBenefit: "Meja belajar rapi meningkatkan konsentrasi belajar hingga 40% dan mencegah buku PR terselip hilang."
  },
  {
    id: "dek-4",
    pillar: "dekomposisi",
    pillarNumber: 4,
    title: "Jadwal Belajar Ujian Akhir Semester (PAS)",
    subtitle: "Pilar Dekomposisi • Membagi beban 12 mata pelajaran dalam 6 hari",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Ada 12 mata pelajaran yang harus diujikan dalam 6 hari. Siswa sering kewalahan jika tidak membagi mata pelajaran berdasarkan tingkat kesulitan (Hafalan, Hitungan, dan Teori Praktik).",
    studentChallenge: "Kelompokkan mata pelajaran ke dalam metode belajar: 'Eksakta / Hitungan', 'Sosial / Hafalan Konsep', dan 'Keterampilan / Praktik'.",
    instruction: "Bagi mata pelajaran berikut ke dalam kategori teknik belajarnya agar jadwal harian seimbang.",
    gameType: "categorize",
    categories: ["Eksakta / Hitungan", "Sosial / Hafalan Konsep", "Keterampilan / Praktik"],
    items: [
      { id: "d4-1", label: "Matematika Wajib & Fisika", category: "Eksakta / Hitungan" },
      { id: "d4-2", label: "Kimia & Ekonomi Akuntansi", category: "Eksakta / Hitungan" },
      { id: "d4-3", label: "Sejarah Indonesia & Sosiologi", category: "Sosial / Hafalan Konsep" },
      { id: "d4-4", label: "PPKn & Geografi", category: "Sosial / Hafalan Konsep" },
      { id: "d4-5", label: "Informatika (Coding / Algoritma)", category: "Keterampilan / Praktik" },
      { id: "d4-6", label: "Seni Budaya & Prakarya (PKWU)", category: "Keterampilan / Praktik" },
    ],
    hint: "Eksakta butuh latihan rumus, Sosial butuh peta konsep/mind mapping, Praktik butuh simulasi langsung.",
    ctExplanation: "Dekomposisi kurikulum memungkinkan siswa berganti fokus otak (kiri & kanan) sehingga tidak cepat lelah secara kognitif.",
    dailyLifeBenefit: "Menghindari sistem kebut semalam (SKS) yang merusak kesehatan dan menghasilkan nilai ujian maksimal."
  },
  {
    id: "dek-5",
    pillar: "dekomposisi",
    pillarNumber: 5,
    title: "Produksi Video Tugas Kelompok Sejarah",
    subtitle: "Pilar Dekomposisi • Membagi alur pembuatan video dari naskah hingga tayang",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Guru Sejarah memberikan tugas membuat video dokumenter drama proklamasi berdurasi 7 menit. Jika tidak dibagi dengan rapi, anggota kelompok akan saling lempar tanggung jawab.",
    studentChallenge: "Pecah produksi video ke dalam 3 tahapan industri kreatif: 'Pra-Produksi', 'Produksi (Syuting)', dan 'Pasca-Produksi'.",
    instruction: "Petakan tugas-tugas tim video ke fase kerja yang tepat.",
    gameType: "categorize",
    categories: ["Pra-Produksi", "Produksi (Syuting)", "Pasca-Produksi"],
    items: [
      { id: "d5-1", label: "Riset Fakta Sejarah & Tulis Naskah", category: "Pra-Produksi" },
      { id: "d5-2", label: "Pemilihan Kostum & Lokasi Museum", category: "Pra-Produksi" },
      { id: "d5-3", label: "Perekaman Adegan Kamera & Rekam Suara", category: "Produksi (Syuting)" },
      { id: "d5-4", label: "Pementasan Akting Tokoh Proklamasi", category: "Produksi (Syuting)" },
      { id: "d5-5", label: "Pemotongan Klip Video & Koreksi Warna", category: "Pasca-Produksi" },
      { id: "d5-6", label: "Penambahan Musik Latar & Ekspor MP4", category: "Pasca-Produksi" },
    ],
    hint: "Pra-produksi adalah perencanaan, Produksi adalah saat kamera menyala di lokasi, Pasca-produksi adalah editing di laptop.",
    ctExplanation: "Struktur dekomposisi kerja (Work Breakdown Structure) adalah standar profesional di dunia rekayasa perangkat lunak dan multimedia.",
    dailyLifeBenefit: "Kerja kelompok selesai tepat waktu dan setiap anggota memiliki pembagian tugas yang adil."
  },
  {
    id: "dek-6",
    pillar: "dekomposisi",
    pillarNumber: 6,
    title: "Mengelola Anggaran Uang Saku Mingguan Pelajar",
    subtitle: "Pilar Dekomposisi • Membagi pos keuangan Rp 150.000 / minggu",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Kamu diberikan uang saku mingguan Rp 150.000 oleh orang tua untuk kebutuhan sekolah dari Senin sampai Jumat. Sering kali uang habis di hari Rabu karena tidak dikelompokkan.",
    studentChallenge: "Pecah alokasi uang saku ke dalam: 'Kebutuhan Wajib Harian', 'Kebutuhan Akademik Sekolah', dan 'Tabungan & Dana Darurat'.",
    instruction: "Kelompokkan pos-pos pengeluaran berikut agar keuanganmu sehat sampai akhir pekan.",
    gameType: "categorize",
    categories: ["Kebutuhan Wajib Harian", "Kebutuhan Akademik Sekolah", "Tabungan & Dana Darurat"],
    items: [
      { id: "d6-1", label: "Ongkos Angkot / Bensin Motor PP", category: "Kebutuhan Wajib Harian" },
      { id: "d6-2", label: "Makan Siang di Kantin Sekolah", category: "Kebutuhan Wajib Harian" },
      { id: "d6-3", label: "Iuran Uang Kas Kelas Mingguan", category: "Kebutuhan Akademik Sekolah" },
      { id: "d6-4", label: "Fotokopi LKS & Cetak Makalah", category: "Kebutuhan Akademik Sekolah" },
      { id: "d6-5", label: "Disisihkan ke Celengan Rp 20.000", category: "Tabungan & Dana Darurat" },
      { id: "d6-6", label: "Cadangan Tambal Ban / Beli Obat UKS", category: "Tabungan & Dana Darurat" },
    ],
    hint: "Kebutuhan wajib adalah pengeluaran hidup setiap hari, akademik untuk tugas sekolah, sisanya tabungan pengaman.",
    ctExplanation: "Dekomposisi keuangan memisahkan variabel cost dan fixed cost sehingga mencegah defisit di tengah jalan.",
    dailyLifeBenefit: "Tidak pernah kehabisan uang ongkos pulang sekolah dan mampu membeli buku impian dari hasil tabungan sendiri."
  },
  {
    id: "dek-7",
    pillar: "dekomposisi",
    pillarNumber: 7,
    title: "Merancang Stand Bazar Kewirausahaan (PKWU)",
    subtitle: "Pilar Dekomposisi • Membagi modul bisnis jualan makanan di sekolah",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Kelas X-3 akan membuka stand bazar makanan tradisional kekinian di hari ulang tahun sekolah. Keberhasilan stand memerlukan koordinasi terstruktur.",
    studentChallenge: "Petakan tugas tim bazar ke dalam divisi: 'Divisi Produk & Dapur', 'Divisi Dekorasi & Stand', dan 'Divisi Kasir & Pemasaran'.",
    instruction: "Distribusikan rincian pekerjaan berikut ke divisi yang tepat.",
    gameType: "categorize",
    categories: ["Divisi Produk & Dapur", "Divisi Dekorasi & Stand", "Divisi Kasir & Pemasaran"],
    items: [
      { id: "d7-1", label: "Belanja Bahan Baku Pisang Nugget", category: "Divisi Produk & Dapur" },
      { id: "d7-2", label: "Pengemasan Kotak Makanan Higienis", category: "Divisi Produk & Dapur" },
      { id: "d7-3", label: "Menghias Meja Stand dengan Banner & Lampu", category: "Divisi Dekorasi & Stand" },
      { id: "d7-4", label: "Penyusunan Tempat Sampah & Kebersihan Meja", category: "Divisi Dekorasi & Stand" },
      { id: "d7-5", label: "Pembuatan QRIS Pembayaran & Catatan Kasir", category: "Divisi Kasir & Pemasaran" },
      { id: "d7-6", label: "Unggah Video Teaser Promosi di Instagram Kelas", category: "Divisi Kasir & Pemasaran" },
    ],
    hint: "Dapur fokus pada makanan, Dekorasi fokus pada fisik stand, Pemasaran fokus pada uang dan promosi.",
    ctExplanation: "Dalam rekayasa sistem terdistribusi, dekomposisi fungsional memungkinkan tim bekerja secara asinkron tanpa tabrakan wewenang.",
    dailyLifeBenefit: "Stand bazar meraup laba bersih tinggi tanpa kericuhan di meja kasir saat jam istirahat ramai."
  },
  {
    id: "dek-8",
    pillar: "dekomposisi",
    pillarNumber: 8,
    title: "Merancang Acara Pentas Seni (Pensi) OSIS",
    subtitle: "Pilar Dekomposisi • Membedah kepanitiaan festival sekolah 1.000 penonton",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "OSIS SMA merencanakan pensi akbar dengan menghadirkan bintang tamu musisi nasional. Ada izin kepolisian, sound system, sponsor komersial, dan crowd control.",
    studentChallenge: "Kelompokkan tanggung jawab kepanitiaan ke dalam 3 sektor krusial: 'Sektor Acara & Pengisi Acara', 'Sektor Teknis Panggung & Sound', dan 'Sektor Humas, Izin & Keamanan'.",
    instruction: "Petakan perizinan dan peralatan berikut ke sektor penanggung jawabnya.",
    gameType: "categorize",
    categories: ["Sektor Acara & Pengisi Acara", "Sektor Teknis Panggung & Sound", "Sektor Humas, Izin & Keamanan"],
    items: [
      { id: "d8-1", label: "Rundown Menit ke Menit Penampilan Ekstrakurikuler", category: "Sektor Acara & Pengisi Acara" },
      { id: "d8-2", label: "Rider Makanan & Hotel Guest Star", category: "Sektor Acara & Pengisi Acara" },
      { id: "d8-3", label: "Genset Listrik 40.000 Watt & Rigging Panggung", category: "Sektor Teknis Panggung & Sound" },
      { id: "d8-4", label: "Mikrofon Wireless, Lighting & Speaker Line Array", category: "Sektor Teknis Panggung & Sound" },
      { id: "d8-5", label: "Surat Izin Keramaian Polsek & Puskesmas", category: "Sektor Humas, Izin & Keamanan" },
      { id: "d8-6", label: "Gelang Tiket Masuk & Jalur Evakuasi Darurat", category: "Sektor Humas, Izin & Keamanan" },
    ],
    hint: "Bedakan mana konten pentas seni, mana infrastruktur kelistrikan/panggung, dan mana urusan legalitas keamanan.",
    ctExplanation: "Pensi skala besar tidak mungkin dikomando oleh satu orang. Dekomposisi modular memisahkan arsitektur acara menjadi sub-sistem yang mandiri.",
    dailyLifeBenefit: "Acara sekolah berlangsung spektakuler, aman, tertib, dan tidak dibubarkan pihak keamanan."
  },
  {
    id: "dek-9",
    pillar: "dekomposisi",
    pillarNumber: 9,
    title: "Troubleshooting Komputer Lab Tidak Konek Internet",
    subtitle: "Pilar Dekomposisi • Mengurai masalah jaringan menjadi 3 lapisan (Layer)",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Saat simulasi asesmen nasional di Lab Komputer, 1 PC siswa tidak bisa membuka situs ujian (tanda seru kuning di ikon WiFi/LAN).",
    studentChallenge: "Dekomposisikan pengecekan masalah jaringan komputer ke dalam 3 layer: 'Lapisan Fisik (Hardware)', 'Lapisan Logika (Sistem Operasi/IP)', dan 'Lapisan Layanan Server/Browser'.",
    instruction: "Tempatkan tindakan troubleshooting ke lapisan yang bersangkutan.",
    gameType: "categorize",
    categories: ["Lapisan Fisik (Hardware)", "Lapisan Logika (Sistem Operasi/IP)", "Lapisan Layanan Server/Browser"],
    items: [
      { id: "d9-1", label: "Cek apakah lampu indikator kabel LAN menyala hijau", category: "Lapisan Fisik (Hardware)" },
      { id: "d9-2", label: "Pastikan port switch hub tidak goyang atau terlepas", category: "Lapisan Fisik (Hardware)" },
      { id: "d9-3", label: "Periksa IP Address 192.168.1.X dan Subnet Mask di CMD", category: "Lapisan Logika (Sistem Operasi/IP)" },
      { id: "d9-4", label: "Lakukan tes ping ke default gateway router sekolah", category: "Lapisan Logika (Sistem Operasi/IP)" },
      { id: "d9-5", label: "Hapus cache history browser Chrome dan reload DNS", category: "Lapisan Layanan Server/Browser" },
      { id: "d9-6", label: "Periksa apakah server CBT lokal sekolah sedang down", category: "Lapisan Layanan Server/Browser" },
    ],
    hint: "Fisik berhubungan dengan kabel dan port. Logika berhubungan dengan konfigurasi IP dan Ping. Layanan berhubungan dengan browser dan web server.",
    ctExplanation: "Ini adalah penerapan nyata model OSI Layer dalam ilmu jaringan komputer menggunakan dekomposisi analitis.",
    dailyLifeBenefit: "Mampu memperbaiki koneksi internet PC sendiri dalam 2 menit tanpa harus memanggil teknisi laboratorium."
  },
  {
    id: "dek-10",
    pillar: "dekomposisi",
    pillarNumber: 10,
    title: "Merencanakan Study Tour / Kunjungan Industri",
    subtitle: "Pilar Dekomposisi • Membedah logistik perjalanan 150 siswa lintas kota",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Angkatan kelas X akan mengadakan kunjungan industri ke pabrik teknologi dan museum sejarah di luar kota selama 3 hari 2 malam.",
    studentChallenge: "Bagi manajemen perjalanan menjadi: 'Rute & Transportasi Armada', 'Jadwal Agenda Kunjungan Edukasi', dan 'Akomodasi & Konsumsi'.",
    instruction: "Klasifikasikan rincian perencanaan berikut ke dalam pilar logistik yang tepat.",
    gameType: "categorize",
    categories: ["Rute & Transportasi Armada", "Jadwal Agenda Kunjungan Edukasi", "Akomodasi & Konsumsi"],
    items: [
      { id: "d10-1", label: "Sewa 3 Unit Bus Pariwisata & Tiket Tol", category: "Rute & Transportasi Armada" },
      { id: "d10-2", label: "Jadwal Istirahat di Rest Area Tol KM 166", category: "Rute & Transportasi Armada" },
      { id: "d10-3", label: "Surat Konfirmasi Kunjungan Pabrik Robotika", category: "Jadwal Agenda Kunjungan Edukasi" },
      { id: "d10-4", label: "Pemandu Edukasi Museum & Lembar Kerja Siswa", category: "Jadwal Agenda Kunjungan Edukasi" },
      { id: "d10-5", label: "Pemesanan 45 Kamar Hotel Siswa & Guru", category: "Akomodasi & Konsumsi" },
      { id: "d10-6", label: "Katering Nasi Kotak Siang & Air Mineral Dus", category: "Akomodasi & Konsumsi" },
    ],
    hint: "Pisahkan kendaraan jalan raya, materi belajar siswa di lokasi, dan tempat menginap/makan.",
    ctExplanation: "Logistik skala besar memisahkan mobilitas spasial dari kegiatan temporal demi menjamin keselamatan rombongan.",
    dailyLifeBenefit: "Perjalanan edukasi berlangsung menyenangkan, hemat biaya, dan semua siswa selamat sampai tujuan."
  },

  // ==========================================
  // 2. PENGENALAN POLA (10 SIMULATOR KEHIDUPAN SISWA)
  // ==========================================
  {
    id: "pol-1",
    pillar: "pola",
    pillarNumber: 1,
    title: "Pola Siklus Lampu Merah Menuju Sekolah",
    subtitle: "Pilar Pengenalan Pola • Menghitung siklus detik lampu persimpangan jalan",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Setiap pagi sepeda motormu melewati persimpangan jalan menuju sekolah. Lampu lalu lintas memiliki durasi tetap: Merah (60 detik), Kuning (5 detik), Hijau (25 detik). Total 1 siklus = 90 detik.",
    studentChallenge: "Jika kamu tiba di persimpangan saat detik ke-10 lampu MERAH baru menyala, berapa detik lagi kamu harus menunggu sebelum kendaraanmu boleh jalan (lampu HIJAU menyala)?",
    instruction: "Temukan pola sisa waktu lampu merah hingga berubah menjadi hijau.",
    gameType: "pattern_detect",
    items: [
      { id: "p1-opt1", label: "30 Detik", isCorrect: false },
      { id: "p1-opt2", label: "50 Detik", isCorrect: true, details: "Lampu merah berdurasi 60 detik. Karena baru berjalan 10 detik, sisa waktu merah = 60 - 10 = 50 detik hingga lampu hijau menyala." },
      { id: "p1-opt3", label: "75 Detik", isCorrect: false },
      { id: "p1-opt4", label: "90 Detik", isCorrect: false },
    ],
    hint: "Kamu baru menghabiskan 10 detik dari 60 detik total durasi lampu merah.",
    ctExplanation: "Pengenalan pola periodik (state machine siklis) memungkinkan kita memprediksi waktu tunggu dengan rumus matematika sederhana.",
    dailyLifeBenefit: "Dapat memperkirakan waktu berangkat dari rumah sehingga tidak terburu-buru dan tidak terkena lampu merah berulang kali."
  },
  {
    id: "pol-2",
    pillar: "pola",
    pillarNumber: 2,
    title: "Pola Kedatangan Angkot Sekolah",
    subtitle: "Pilar Pengenalan Pola • Menemukan pola interval kedatangan kendaraan umum",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Catatan kedatangan Angkot 02 di halte sekolah menunjukkan waktu: 06.05, 06.17, 06.29, 06.41. Kamu sampai di halte pukul 06.44 karena baru keluar rumah.",
    studentChallenge: "Berdasarkan pola interval waktu kedatangan angkot tersebut, jam berapakah angkot berikutnya akan tiba di halte?",
    instruction: "Identifikasi selisih menit antar angkot dan tentukan jadwal berikutnya.",
    gameType: "pattern_detect",
    items: [
      { id: "p2-opt1", label: "06.48", isCorrect: false },
      { id: "p2-opt2", label: "06.53", isCorrect: true, details: "Pola selisih waktu adalah bertambah 12 menit setiap kedatangan (06.05 -> 06.17 -> 06.29 -> 06.41). Maka berikutnya adalah 06.41 + 12 menit = 06.53." },
      { id: "p2-opt3", label: "06.58", isCorrect: false },
      { id: "p2-opt4", label: "07.02", isCorrect: false },
    ],
    hint: "Hitung selisih dari 06.05 ke 06.17, lalu dari 06.17 ke 06.29. Berapa menit penambahannya?",
    ctExplanation: "Deret aritmetika waktu adalah contoh dasar pengenalan pola dalam analisis data transportasi publik.",
    dailyLifeBenefit: "Menghindari berdiri menunggu terlalu lama di pinggir jalan dan tahu persis kapan harus keluar rumah."
  },
  {
    id: "pol-3",
    pillar: "pola",
    pillarNumber: 3,
    title: "Pola Jam Ramai Antrean Kantin Sekolah",
    subtitle: "Pilar Pengenalan Pola • Menghindari kerumunan jam istirahat pertama",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Istirahat sekolah berlangsung 30 menit (09.45 - 10.15). Data antrean kasir kantin: Menit ke-0 s.d 10 (Sangat Ramai, antre 15 menit), Menit ke-11 s.d 20 (Sedang, antre 6 menit), Menit ke-21 s.d 30 (Sepi, namun banyak makanan habis).",
    studentChallenge: "Pola strategi pembelian manakah yang paling cerdas agar siswa tetap dapat makanan enak tanpa menghabiskan seluruh jam istirahat hanya untuk mengantre?",
    instruction: "Pilih pola perilaku yang paling optimal berdasarkan data antrean.",
    gameType: "pattern_detect",
    items: [
      { id: "p3-opt1", label: "Lari secepatnya di menit ke-0 dan ikut berdesakan di depan kasir", isCorrect: false },
      { id: "p3-opt2", label: "Pergi ke kantin pada menit ke-12 s.d 15 (antrean sudah mencair, menu masih lengkap)", isCorrect: true, details: "Pola optimal: gelombang pertama murid yang berdesakan sudah selesai dilayani, antrean turun drastis ke 4-6 menit, dan makanan belum habis." },
      { id: "p3-opt3", label: "Menunggu di menit ke-28 saat bel masuk hampir berbunyi", isCorrect: false },
      { id: "p3-opt4", label: "Tidak jajan sama sekali selama 3 tahun sekolah", isCorrect: false },
    ],
    hint: "Cari titik keseimbangan (sweet spot) antara antrean yang sudah berkurang dan ketersediaan makanan.",
    ctExplanation: "Ini adalah pengenalan pola antrean (Queuing Theory) yang digunakan dalam optimasi server cloud dan sistem kasir modern.",
    dailyLifeBenefit: "Bisa menikmati makan siang santai dengan teman tanpa takut telat masuk kelas setelah bel berbunyi."
  },
  {
    id: "pol-4",
    pillar: "pola",
    pillarNumber: 4,
    title: "Pola Deret Nomor Meja Ujian CBT",
    subtitle: "Pilar Pengenalan Pola • Menemukan aturan penomoran ruangan kelas ujian",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Denah meja ujian CBT sekolah diatur dalam pola baris: Baris 1: Meja 01, 04, 07, 10. Baris 2: Meja 02, 05, 08, 11. Baris 3: Meja 03, 06, 09, 12.",
    studentChallenge: "Jika nomor ujianmu adalah Meja 22, berada di Baris ke berapakah mejamu?",
    instruction: "Analisis pola sisa bagi (modulus) penomoran meja ujian.",
    gameType: "pattern_detect",
    items: [
      { id: "p4-opt1", label: "Baris 1 (Pola: angka kelipatan 3 ditambah 1)", isCorrect: true, details: "Pola Baris 1 adalah angka modulo 3 bersisa 1 (1, 4, 7, 10, 13, 16, 19, 22). Karena 22 = (3 x 7) + 1, meja 22 berada di Baris 1." },
      { id: "p4-opt2", label: "Baris 2 (Pola: angka kelipatan 3 ditambah 2)", isCorrect: false },
      { id: "p4-opt3", label: "Baris 3 (Pola: angka kelipatan 3 pas)", isCorrect: false },
      { id: "p4-opt4", label: "Tidak berada di ruangan ini", isCorrect: false },
    ],
    hint: "Bagi nomor mejamu dengan 3. Berapa angka sisanya?",
    ctExplanation: "Operator Modulo (sisa bagi) adalah pondasi penting dalam algoritma hashing dan partisi tabel database.",
    dailyLifeBenefit: "Langsung menemukan bangku ujian dalam 5 detik tanpa perlu berkeliling memeriksa satu per satu label meja."
  },
  {
    id: "pol-5",
    pillar: "pola",
    pillarNumber: 5,
    title: "Pola Prediksi Cuaca Membawa Payung/Jas Hujan",
    subtitle: "Pilar Pengenalan Pola • Korelasi awan mendung, jam sore, dan probabilitas hujan",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Dalam sebulan terakhir, kamu mencatat: Jika pagi hari sangat terik dan siang jam 14.00 mulai terlihat awan kumulonimbus tebal di arah barat, maka 90% terjadi hujan lebat saat jam pulang sekolah pukul 15.30.",
    studentChallenge: "Hari ini pukul 13.45 langit barat menggelap pekat dan suhu udara mendadak turun dingin. Keputusan berbasis pola apakah yang paling tepat?",
    instruction: "Identifikasi kesamaan pola historis dan tentukan aksi pencegahannya.",
    gameType: "pattern_detect",
    items: [
      { id: "p5-opt1", label: "Meninggalkan helm di spion motor tanpa ditutup plastik karena mengira tidak akan hujan", isCorrect: false },
      { id: "p5-opt2", label: "Segera amankan helm ke dalam bagasi/jok motor dan siapkan jas hujan di tas sebelum bel pulang", isCorrect: true, details: "Pola tanda-tanda alam (awan barat + angin dingin) cocok persis dengan pola 90% hujan lebat jam pulang sekolah." },
      { id: "p5-opt3", label: "Menunggu sampai hujan deras baru mencari kantong kresek", isCorrect: false },
      { id: "p5-opt4", label: "Pulang jalan kaki di bawah petir", isCorrect: false },
    ],
    hint: "Gunakan data historis untuk mengambil tindakan preventif sebelum peristiwa terjadi.",
    ctExplanation: "Ini adalah dasar dari predictive modeling dan machine learning klasifikasi cuaca berbasis sensor lingkungan.",
    dailyLifeBenefit: "Seragam dan buku pelajaran tetap kering terlindungi, serta helm tidak basah terkena air hujan."
  },
  {
    id: "pol-6",
    pillar: "pola",
    pillarNumber: 6,
    title: "Pola Konsumsi Kuota Internet Belajar",
    subtitle: "Pilar Pengenalan Pola • Analisis penyebab kuota bulanan cepat habis",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Kuota internetmu 10 GB habis hanya dalam 10 hari. Hasil pengecekan log: Membaca teks materi PDF (2 MB/jam), Chat WhatsApp tugas (5 MB/jam), Streaming video TikTok/Reels kualitas tinggi (600 MB/jam).",
    studentChallenge: "Pola anomali apakah yang menyebabkan kuota belajar bulananmu boros 30 kali lipat dari semestinya?",
    instruction: "Temukan komponen aktivitas yang mendominasi konsumsi data.",
    gameType: "pattern_detect",
    items: [
      { id: "p6-opt1", label: "Aktivitas mengirim pesan teks di grup kelas", isCorrect: false },
      { id: "p6-opt2", label: "Aktivitas membuka file PDF modul rangkuman guru", isCorrect: false },
      { id: "p6-opt3", label: "Aktivitas scrolling video beresolusi tinggi di luar kebutuhan belajar", isCorrect: true, details: "Pola data menunjukkan video memakan 600 MB/jam, menyedot 90% total kapasitas kuota hanya dalam beberapa jam scrolling." },
      { id: "p6-opt4", label: "Aplikasi kalkulator bawaan smartphone", isCorrect: false },
    ],
    hint: "Bandingkan angka MB dari masing-masing jenis aktivitas aplikasi.",
    ctExplanation: "Profiling resource usage adalah keterampilan mendasar engineer dalam mendiagnosis memory leak dan bandwidth hog.",
    dailyLifeBenefit: "Kuota internet cukup sepanjang bulan dan uang saku tidak habis hanya untuk membeli paket data tambahan."
  },
  {
    id: "pol-7",
    pillar: "pola",
    pillarNumber: 7,
    title: "Deteksi Pola Pesan Phishing / Hoax di Grup Kelas",
    subtitle: "Pilar Pengenalan Pola • Mengenali ciri-ciri tautan jebakan penipuan",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Di grup WhatsApp kelas masuk pesan: 'KEMENDIKBUD BAGIKAN SUBSIDI KUOTA 50GB GRATIS! KLIK LINK: http://kuota-gratis-kemdikbud.xyz-promo.biz SEBELUM HANGUS MALAM INI!'.",
    studentChallenge: "Manakah 3 pola ciri khas serangan phising/social engineering pada pesan di atas?",
    instruction: "Analisis ciri umum dari pesan penipuan siber.",
    gameType: "pattern_detect",
    items: [
      { id: "p7-opt1", label: "Domain resmi berakhiran .go.id dan tanpa batas waktu", isCorrect: false },
      { id: "p7-opt2", label: "Pola domain aneh (.xyz-promo.biz), rasa urgensi palsu ('sebelum hangus'), dan tawaran gratisan tidak masuk akal", isCorrect: true, details: "Penipu selalu menggunakan 3 pola: iming-iming hadiah besar, domain bajakan palsu, dan menciptakan kepanikan agar korban tidak berpikir kritis." },
      { id: "p7-opt3", label: "Dikirim oleh guru pengampu wali kelas", isCorrect: false },
      { id: "p7-opt4", label: "Pesan memiliki tanda tangan digital bersertifikat", isCorrect: false },
    ],
    hint: "Perhatikan alamat situs webnya, apakah itu domain resmi pemerintah (.go.id) atau domain acak murahan?",
    ctExplanation: "Pattern recognition adalah benteng utama sistem keamanan informasi (IDS/Antivirus) dalam mendeteksi malware dan phishing.",
    dailyLifeBenefit: "Akun media sosial dan data pribadi siswa terlindung dari pembobolan hacker serta ransomware."
  },
  {
    id: "pol-8",
    pillar: "pola",
    pillarNumber: 8,
    title: "Pola Ritme Belajar & Nilai Rapor",
    subtitle: "Pilar Pengenalan Pola • Korelasi jam tidur, latihan soal, dan daya ingat",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Rani menganalisis pola nilainya: Saat tidur larut malam jam 02.00 dan belajar sistem SKS, nilai ujian rata-rata 62 dan kepala pusing. Saat belajar 45 menit setiap sore dan tidur jam 22.00, nilai ujian stabil 88.",
    studentChallenge: "Kesimpulan pola belajar jangka panjang apakah yang terbukti secara komputasi psikologis?",
    instruction: "Identifikasi korelasi positif antar variabel kebiasaan.",
    gameType: "pattern_detect",
    items: [
      { id: "p8-opt1", label: "Belajar semalaman suntuk tanpa tidur adalah cara terbaik meraih nilai 100", isCorrect: false },
      { id: "p8-opt2", label: "Pola konsistensi terdistribusi (spaced repetition) dengan istirahat cukup menghasilkan retensi memori jangka panjang tertinggi", isCorrect: true, details: "Pola neurosains membuktikan otak melakukan konsolidasi memori selama tidur REM; SKS menyebabkan informasi cepat menguap dalam hitungan jam." },
      { id: "p8-opt3", label: "Nilai ujian hanya bergantung pada keberuntungan lembar jawaban", isCorrect: false },
      { id: "p8-opt4", label: "Makan cokelat saat ujian menggantikan fungsi belajar selama 3 bulan", isCorrect: false },
    ],
    hint: "Cari pola kebiasaan yang berulang dengan hasil nilai tertinggi yang konsisten.",
    ctExplanation: "Dalam data mining, ini disebut Analisis Regresi dan Korelasi Antara Input (Kebiasaan) dan Output (Performa).",
    dailyLifeBenefit: "Meraih ranking tinggi tanpa stres berlebihan dan badan tetap bugar berenergi di sekolah."
  },
  {
    id: "pol-9",
    pillar: "pola",
    pillarNumber: 9,
    title: "Pola Tren Peminjaman Buku Perpustakaan",
    subtitle: "Pilar Pengenalan Pola • Memprediksi waktu perebutan buku referensi",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Data pustakawan selama 3 semester: Buku paket latihan soal SBMPTN/UTBK selalu ludes dipinjam 2 minggu sebelum pekan tryout. Pada awal semester, rak tersebut 80% kosong peminjam.",
    studentChallenge: "Pola tindakan preventif apakah yang harus dilakukan siswa kelas X yang ingin meminjam buku referensi tersebut tanpa kehabisan?",
    instruction: "Gunakan pola musiman (seasonality trend) untuk menentukan momentum aksi.",
    gameType: "pattern_detect",
    items: [
      { id: "p9-opt1", label: "Datang ke perpustakaan 1 hari sebelum ujian saat buku sudah habis dipinjam kakak kelas", isCorrect: false },
      { id: "p9-opt2", label: "Meminjam atau memfotokopi bab materi penting pada 3-4 minggu sebelum pekan ujian ketika stok masih melimpah di rak", isCorrect: true, details: "Memanfaatkan siklus rendah (low-demand phase) sebelum kurva permintaan melonjak drastis (peak-demand phase)." },
      { id: "p9-opt3", label: "Menyembunyikan buku perpustakaan di bawah kasur asrama", isCorrect: false },
      { id: "p9-opt4", label: "Meminta pustakawan membeli 10.000 buku baru besok pagi", isCorrect: false },
    ],
    hint: "Kapan stok buku paling sepi peminat dalam siklus semesteran?",
    ctExplanation: "Ini adalah pengenalan pola musiman (Seasonal Time Series Trend) yang digunakan dalam manajemen rantai pasok (Supply Chain).",
    dailyLifeBenefit: "Mendapatkan materi belajar terbaik lebih awal tanpa harus berebut antrean dengan ratusan siswa lainnya."
  },
  {
    id: "pol-10",
    pillar: "pola",
    pillarNumber: 10,
    title: "Pola Barisan Logika Kode Sandi Pramuka / Komputer",
    subtitle: "Pilar Pengenalan Pola • Memecahkan sandi biner kelipatan 2",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Saat lomba penjelajahan Pramuka, kelompokmu menemukan teka-teki sandi pos komando: [1, 2, 4, 8, 16, 32, X, Y]. Di dunia informatika, ini adalah nilai bobot bit biner (2^n).",
    studentChallenge: "Berapakah nilai angka X dan Y berikutnya yang melengkapi pola barisan tersebut?",
    instruction: "Temukan pola kelipatan eksponensial basis 2.",
    gameType: "pattern_detect",
    items: [
      { id: "p10-opt1", label: "X = 40, Y = 48", isCorrect: false },
      { id: "p10-opt2", label: "X = 48, Y = 64", isCorrect: false },
      { id: "p10-opt3", label: "X = 64, Y = 128", isCorrect: true, details: "Pola adalah perkalian 2 (eksponen basis 2). Setelah 32 adalah 32x2 = 64 (X), dan 64x2 = 128 (Y). Ini adalah dasar arsitektur memori RAM 64-bit dan 128-bit!" },
      { id: "p10-opt4", label: "X = 60, Y = 100", isCorrect: false },
    ],
    hint: "Setiap angka merupakan hasil kali 2 dari angka sebelumnya.",
    ctExplanation: "Sistem bilangan biner (pangkat 2) adalah bahasa paling fundamental yang menggerakkan seluruh mikroprosesor di dunia.",
    dailyLifeBenefit: "Memahami kapasitas RAM/SSD smartphone (32GB, 64GB, 128GB, 256GB) dan memenangkan lomba logika sekolah."
  },

  // ==========================================
  // 3. ABSTRAKSI (10 SIMULATOR KEHIDUPAN SISWA)
  // ==========================================
  {
    id: "abs-1",
    pillar: "abstraksi",
    pillarNumber: 1,
    title: "Membaca Denah Gedung Sekolah",
    subtitle: "Pilar Abstraksi • Menyaring informasi ruang esensial vs detail visual dekoratif",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Siswa baru kelas X ingin mencari letak 'Laboratorium Komputer 2' di denah sekolah. Denah yang baik tidak perlu menggambar setiap daun pohon, motif keramik, atau warna gorden jendela.",
    studentChallenge: "Pilih 3 informasi mana yang PALING PENTING (ESENSIAL) untuk peta penunjuk arah gedung sekolah!",
    instruction: "Centang informasi esensial dan abaikan detail dekoratif yang tidak relevan.",
    gameType: "filter_essential",
    items: [
      { id: "a1-1", label: "Nama Ruangan & Nomor Lantai (Gedung B Lantai 2)", isEssential: true },
      { id: "a1-2", label: "Posisi Tangga & Pintu Masuk Lorong", isEssential: true },
      { id: "a1-3", label: "Arah Mata Angin / Tanda 'Anda di Sini'", isEssential: true },
      { id: "a1-4", label: "Warna cat pintu kamar mandi", isEssential: false },
      { id: "a1-5", label: "Jumlah keramik putih di lantai koridor", isEssential: false },
      { id: "a1-6", label: "Merk AC dan jenis kipas angin gantung", isEssential: false },
    ],
    correctAnswers: ["a1-1", "a1-2", "a1-3"],
    hint: "Pikirkan apa yang mutlak dibutuhkan orang asing untuk berjalan dari pintu gerbang ke lab komputer.",
    ctExplanation: "Abstraksi menyembunyikan kompleksitas fisik yang tidak relevan sehingga peta mudah dibaca dalam 3 detik.",
    dailyLifeBenefit: "Mampu membaca dan membuat denah lokasi kegiatan ekstrakurikuler yang mudah dimengerti semua orang."
  },
  {
    id: "abs-2",
    pillar: "abstraksi",
    pillarNumber: 2,
    title: "Membuat Kartu Pelajar Digital",
    subtitle: "Pilar Abstraksi • Menyaring data identitas resmi vs informasi pribadi tidak relevan",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Sekolah ingin mencetak Kartu Pelajar berukuran kartu ATM (8.5 cm x 5.4 cm). Ruang pada kartu sangat terbatas dan hanya boleh memuat data legalitas kesiswaan.",
    studentChallenge: "Pilih 3 data mana yang WAJIB dimasukkan ke dalam Kartu Pelajar resmi!",
    instruction: "Pilih atribut data esensial untuk identitas resmi siswa.",
    gameType: "filter_essential",
    items: [
      { id: "a2-1", label: "Nomor Induk Siswa Nasional (NISN) & Pasfoto Resmi", isEssential: true },
      { id: "a2-2", label: "Nama Lengkap & Kelas/Rombel Siswa", isEssential: true },
      { id: "a2-3", label: "Nama Sekolah & Tanda Tangan Kepala Sekolah", isEssential: true },
      { id: "a2-4", label: "Warna baju dan merk sepatu kesukaan siswa", isEssential: false },
      { id: "a2-5", label: "Daftar 10 lagu favorit di Spotify", isEssential: false },
      { id: "a2-6", label: "Nama hewan peliharaan kucing di rumah", isEssential: false },
    ],
    correctAnswers: ["a2-1", "a2-2", "a2-3"],
    hint: "Kartu pelajar digunakan untuk verifikasi ujian dan perpustakaan. Data apa yang sah secara hukum?",
    ctExplanation: "Dalam perancangan basis data relasional, abstraksi menentukan 'Field / Attribute' yang valid untuk tabel Siswa.",
    dailyLifeBenefit: "Kartu identitas tampil profesional, hemat ruang, dan melindungi privasi data pribadi siswa."
  },
  {
    id: "abs-3",
    pillar: "abstraksi",
    pillarNumber: 3,
    title: "Memilah Struk Pembelian Koperasi Sekolah",
    subtitle: "Pilar Abstraksi • Fokus pada total nominal uang vs teks slogan promosi",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Bendahara kelas diminta membuat laporan pertanggungjawaban (LPJ) pembelian ATK di koperasi sekolah. Struk kertas memiliki banyak tulisan promosi, nomor mesin kasir, dan slogan.",
    studentChallenge: "Informasi mana yang ESENSIAL untuk dicatat ke dalam buku kas pengeluaran keuangan kelas?",
    instruction: "Pilih 3 komponen penting pembukuan akuntansi.",
    gameType: "filter_essential",
    items: [
      { id: "a3-1", label: "Tanggal Pembelian Transaksi", isEssential: true },
      { id: "a3-2", label: "Rincian Nama Barang & Kuantitas (Jumlah)", isEssential: true },
      { id: "a3-3", label: "Total Nominal Rupiah yang Dibayarkan", isEssential: true },
      { id: "a3-4", label: "Slogan 'Terima Kasih Telah Berbelanja di Toko Kami'", isEssential: false },
      { id: "a3-5", label: "Nomor Seri Seri Serial Mesin Kasir Thermal", isEssential: false },
      { id: "a3-6", label: "Nama kasir shift pagi yang bertugas melayani", isEssential: false },
    ],
    correctAnswers: ["a3-1", "a3-2", "a3-3"],
    hint: "Untuk laporan uang kas, guru hanya perlu tahu uang keluar kapan, untuk beli apa, dan berapa jumlahnya.",
    ctExplanation: "Abstraksi transaksi keuangan menyaring kebisingan data (data noise) sehingga buku kas bersih dan dapat diaudit.",
    dailyLifeBenefit: "Laporan keuangan kelas rapi, tidak ada selisih uang kas, dan dipercaya oleh seluruh teman sekelas."
  },
  {
    id: "abs-4",
    pillar: "abstraksi",
    pillarNumber: 4,
    title: "Rute Gowes Sepeda Menghindari Tanjakan",
    subtitle: "Pilar Abstraksi • Memodelkan jalan sebagai Graf (Jarak & Elevasi)",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Kamu ingin bersepeda ke sekolah. Kamu membuka peta digital. Peta digital tidak perlu menampilkan warna genteng rumah warga, tetapi harus menampilkan kontur tanjakan dan jarak kilometer.",
    studentChallenge: "Pilih data apa saja yang ESENSIAL dimodelkan untuk rute bersepeda hemat tenaga!",
    instruction: "Pilih parameter yang memengaruhi stamina pesepeda.",
    gameType: "filter_essential",
    items: [
      { id: "a4-1", label: "Panjang Jarak Tempuh Jalan (Kilometer)", isEssential: true },
      { id: "a4-2", label: "Ketinggian Tanjakan / Derajat Kemiringan Jalan (Elevasi)", isEssential: true },
      { id: "a4-3", label: "Kualitas Aspal & Adanya Jalur Khusus Sepeda", isEssential: true },
      { id: "a4-4", label: "Warna pagar rumah orang yang dilewati di pinggir jalan", isEssential: false },
      { id: "a4-5", label: "Merk mobil yang sedang parkir di garasi warga", isEssential: false },
      { id: "a4-6", label: "Jenis pohon mangga di pekarangan rumah tetangga", isEssential: false },
    ],
    correctAnswers: ["a4-1", "a4-2", "a4-3"],
    hint: "Fokus pada variabel fisik yang menguras tenaga kayuhan kaki dan keselamatan jalan.",
    ctExplanation: "Aplikasi seperti Google Maps dan Strava mengabstraksikan dunia nyata menjadi graf berbobot (weighted graph).",
    dailyLifeBenefit: "Sampai di sekolah tepat waktu tanpa kelelahan berkeringat basah sebelum pelajaran dimulai."
  },
  {
    id: "abs-5",
    pillar: "abstraksi",
    pillarNumber: 5,
    title: "Formulir Pendaftaran Ekstrakurikuler Paskibra",
    subtitle: "Pilar Abstraksi • Seleksi parameter fisik & medis penting",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Pelatih Paskibraka sekolah membuka seleksi anggota baru. Pelatih membutuhkan data yang tepat untuk penentuan formasi baris-berbaris dan keamanan fisik saat latihan panas terik.",
    studentChallenge: "Pilih 3 kolom data yang PALING RELEVAN untuk formulir seleksi Paskibra!",
    instruction: "Saring data calon anggota paskibra yang benar-benar dibutuhkan.",
    gameType: "filter_essential",
    items: [
      { id: "a5-1", label: "Tinggi Badan & Berat Badan (Proporsional Barisan)", isEssential: true },
      { id: "a5-2", label: "Riwayat Penyakit Medis (Asma, Alergi Matahari, Jantung)", isEssential: true },
      { id: "a5-3", label: "Surat Persetujuan Orang Tua / Wali Siswa", isEssential: true },
      { id: "a5-4", label: "Game online favorit yang sering dimainkan di smartphone", isEssential: false },
      { id: "a5-5", label: "Zodiak dan ramalan horoskop bulan kelahiran", isEssential: false },
      { id: "a5-6", label: "Akun TikTok yang paling sering ditonton saat malam", isEssential: false },
    ],
    correctAnswers: ["a5-1", "a5-2", "a5-3"],
    hint: "Paskibra butuh keselarasan tinggi tubuh dan keselamatan fisik dari riwayat pingsan.",
    ctExplanation: "Abstraksi data mencegah formulir pendaftaran membengkak dengan pertanyaan tidak berguna yang melanggar privasi.",
    dailyLifeBenefit: "Formulir ringkas dan pelatih dapat langsung menyusun pasukan pengibar bendera dengan cepat dan aman."
  },
  {
    id: "abs-6",
    pillar: "abstraksi",
    pillarNumber: 6,
    title: "Membuat Rangkuman Materi Pelajaran Biologi",
    subtitle: "Pilar Abstraksi • Ekstraksi kata kunci & fungsi inti dari buku 50 halaman",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Bab Sistem Peredaran Darah Manusia di buku cetak memiliki 50 halaman penuh dengan teks pengantar, foto sejarah penemu abad ke-17, dan kutipan filsafat.",
    studentChallenge: "Pilih komponen konsep mana yang WAJIB dicatat dalam ringkasan persiapan ujian esok hari!",
    instruction: "Pilih materi esensial biologi dan abaikan cerita pengantar dekoratif.",
    gameType: "filter_essential",
    items: [
      { id: "a6-1", label: "Fungsi Jantung (Bilik & Serambi) dan Pembuluh Darah (Arteri vs Vena)", isEssential: true },
      { id: "a6-2", label: "Alur Peredaran Darah Besar vs Darah Kecil", isEssential: true },
      { id: "a6-3", label: "Komponen Darah (Eritrosit, Leukosit, Trombosit, Plasma) & Penyakitnya", isEssential: true },
      { id: "a6-4", label: "Nama kota tempat kelahiran dokter penemu stetoskop pertama", isEssential: false },
      { id: "a6-5", label: "Puisi pengantar tentang keindahan tubuh manusia di halaman 1", isEssential: false },
      { id: "a6-6", label: "Warna sampul depan buku cetak penerbit edisi revisi", isEssential: false },
    ],
    correctAnswers: ["a6-1", "a6-2", "a6-3"],
    hint: "Fokus pada apa yang akan keluar di soal pilihan ganda dan essay ujian biologi.",
    ctExplanation: "Merangkum adalah proses abstraksi kognitif: memadatkan data besar menjadi representasi mental berbobot tinggi.",
    dailyLifeBenefit: "Waktu belajar berkurang 70% dengan pemahaman konsep yang jauh lebih melekat kuat di otak."
  },
  {
    id: "abs-7",
    pillar: "abstraksi",
    pillarNumber: 7,
    title: "Pemilahan Sampah Sekolah (Tempat Sampah 3 Warna)",
    subtitle: "Pilar Abstraksi • Klasifikasi material berdasarkan sifat penguraian",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Sekolah Adiwiyata menerapkan 3 tong sampah: Hijau (Organik/Mudah Busuk), Kuning (Anorganik/Daur Ulang), dan Merah (Limbah B3/Berbahaya). Kita harus mengabaikan merk produk atau warna bungkus.",
    studentChallenge: "Manakah kriteria abstraksi yang PALING BENAR untuk mengelompokkan sampah?",
    instruction: "Pilih aturan klasifikasi material penguraian sampah.",
    gameType: "filter_essential",
    items: [
      { id: "a7-1", label: "Organik: Sisa makanan, daun gugur, kulit pisang (Dapat dikompos)", isEssential: true },
      { id: "a7-2", label: "Anorganik: Botol plastik, kaleng soda, kertas kardus (Bisa didaur ulang)", isEssential: true },
      { id: "a7-3", label: "B3 Berbahaya: Baterai bekas, pecahan kaca lampu neon, spidol kimia", isEssential: true },
      { id: "a7-4", label: "Mengelompokkan sampah hanya berdasarkan apakah kemasannya bergambar kartun", isEssential: false },
      { id: "a7-5", label: "Mengelompokkan sampah berdasarkan bau wangi atau tidak wangi", isEssential: false },
      { id: "a7-6", label: "Membuang semua sampah ke saluran selokan depan kelas", isEssential: false },
    ],
    correctAnswers: ["a7-1", "a7-2", "a7-3"],
    hint: "Fokus pada sifat kimia bahan pengurainya, bukan pada gambar kemasan atau warnanya.",
    ctExplanation: "Abstraksi memungkinkan generalisasi objek yang tak terhingga menjadi 3 kelas polimorfik yang terkelola.",
    dailyLifeBenefit: "Lingkungan sekolah bersih asri, mengurangi polusi plastik, dan sampah organik bisa jadi pupuk tanaman sekolah."
  },
  {
    id: "abs-8",
    pillar: "abstraksi",
    pillarNumber: 8,
    title: "Perancangan Basis Data Sederhana Perpustakaan",
    subtitle: "Pilar Abstraksi • Memilih entitas relasional untuk sistem peminjaman",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Kamu membuat aplikasi web peminjaman buku perpustakaan sekolah. Sistem memerlukan tabel 'TransaksiPeminjaman'.",
    studentChallenge: "Pilih 3 atribut Foreign Key & Tanggal yang ESENSIAL agar transaksi peminjaman tercatat valid!",
    instruction: "Pilih skema atribut relasional tabel database.",
    gameType: "filter_essential",
    items: [
      { id: "a8-1", label: "NISN Siswa (ID Peminjam) & Kode Barcode Buku", isEssential: true },
      { id: "a8-2", label: "Tanggal Pinjam & Tanggal Jatuh Tempo Pengembalian", isEssential: true },
      { id: "a8-3", label: "Status Peminjaman ('Dipinjam' / 'Sudah Kembali')", isEssential: true },
      { id: "a8-4", label: "Apakah sampul buku ada bekas lipatan halaman kecil", isEssential: false },
      { id: "a8-5", label: "Alasan mengapa siswa memilih membaca buku tersebut", isEssential: false },
      { id: "a8-6", label: "Cuaca saat siswa masuk ke pintu perpustakaan", isEssential: false },
    ],
    correctAnswers: ["a8-1", "a8-2", "a8-3"],
    hint: "Siapa yang pinjam, buku apa yang dipinjam, kapan harus dikembalikan, dan apa statusnya.",
    ctExplanation: "Entity Relationship Diagram (ERD) adalah implementasi murni abstraksi dalam rekayasa data informatika.",
    dailyLifeBenefit: "Sistem pencatatan buku tidak pernah salah data dan denda keterlambatan terhitung otomatis secara adil."
  },
  {
    id: "abs-9",
    pillar: "abstraksi",
    pillarNumber: 9,
    title: "Diagram Alir Presensi Kehadiran Siswa",
    subtitle: "Pilar Abstraksi • Menyederhanakan status kehadiran menjadi 4 status baku",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Sistem e-Rapor Kementerian Pendidikan menyederhanakan kondisi kehadiran ratusan siswa setiap hari ke dalam model status baku.",
    studentChallenge: "Pilih 4 kategori status kehadiran baku yang diakui secara nasional (mengabaikan ribuan alasan personal siswa)!",
    instruction: "Pilih 4 status legal presensi kesiswaan.",
    gameType: "filter_essential",
    items: [
      { id: "a9-1", label: "Hadir (Berada di kelas mengikuti pembelajaran)", isEssential: true },
      { id: "a9-2", label: "Sakit (Disertai surat dokter / pemberitahuan orang tua)", isEssential: true },
      { id: "a9-3", label: "Izin (Keperluan keluarga mendesak / lomba sekolah)", isEssential: true },
      { id: "a9-4", label: "Alpa / Tanpa Keterangan (Tidak hadir tanpa surat)", isEssential: true },
      { id: "a9-5", label: "Status 'Malas Bangun Pagi Karena Main Game'", isEssential: false },
      { id: "a9-6", label: "Status 'Menunggu Hujan Reda Sampai Siang'", isEssential: false },
    ],
    correctAnswers: ["a9-1", "a9-2", "a9-3", "a9-4"],
    hint: "Ingat kolom rekap absensi di rapor: H, S, I, A.",
    ctExplanation: "Abstraksi mengonversi ribuan kondisi subjektif manusia menjadi tipe data Enum (Enumeration) yang pasti.",
    dailyLifeBenefit: "Data kehadiran jelas, transparan, dan tidak menimbulkan perselisihan antara sekolah dan orang tua."
  },
  {
    id: "abs-10",
    pillar: "abstraksi",
    pillarNumber: 10,
    title: "Topologi Wi-Fi Lab & Kelas SMA",
    subtitle: "Pilar Abstraksi • Menyederhanakan jaringan kabel fisik menjadi diagram simpul (Node)",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Guru Informatika meminta siswa menggambarkan skema jaringan internet sekolah. Siswa tidak perlu mengukur panjang setiap meter kabel di plafon gedung.",
    studentChallenge: "Pilih 3 komponen simpul logika yang ESENSIAL untuk memetakan arsitektur jaringan Wi-Fi sekolah!",
    instruction: "Pilih node perangkat jaringan utama.",
    gameType: "filter_essential",
    items: [
      { id: "a10-1", label: "Modem / Router Gateway Internet Sekolah", isEssential: true },
      { id: "a10-2", label: "Switch Hub & Access Point Pemancar Wi-Fi Tiap Lantai", isEssential: true },
      { id: "a10-3", label: "Perangkat Klien Siswa & Komputer Guru (Client Devices)", isEssential: true },
      { id: "a10-4", label: "Warna pembungkus karet kabel LAN biru atau abu-abu", isEssential: false },
      { id: "a10-5", label: "Merk paku klem yang menempel di tembok lorong", isEssential: false },
      { id: "a10-6", label: "Debu yang menempel di casing router", isEssential: false },
    ],
    correctAnswers: ["a10-1", "a10-2", "a10-3"],
    hint: "Fokus pada peran fungsional: Sumber internet -> Penyebar sinyal -> Penerima sinyal.",
    ctExplanation: "Network Topology Diagram adalah abstraksi matematis yang mengubah dunia fisik menjadi Graf Simpul (Nodes & Edges).",
    dailyLifeBenefit: "Dapat mendeteksi titik mana yang rusak saat Wi-Fi sekolah mendadak lambat atau mati."
  },

  // ==========================================
  // 4. ALGORITMA (10 SIMULATOR KEHIDUPAN SISWA)
  // ==========================================
  {
    id: "alg-1",
    pillar: "algoritma",
    pillarNumber: 1,
    title: "Prosedur Memakai Seragam Upacara Senin Lengkap",
    subtitle: "Pilar Algoritma • Urutan instruksi sekuensial memakai seragam dari nol",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Jika urutan memakai seragam terbalik (misalnya memakai sepatu dulu baru memakai celana panjang), kamu akan kesulitan dan membuang waktu.",
    studentChallenge: "Urutkan langkah-langkah berpakaian seragam upacara Senin berikut dari awal hingga akhir dengan benar!",
    instruction: "Susun urutan nomor langkah 1 sampai 5.",
    gameType: "sequence",
    items: [
      { id: "al1-1", label: "Kenakan kemeja putih dan kancingkan dengan rapi", order: 1 },
      { id: "al1-2", label: "Pakai celana/rok abu-abu dan pasang ikat pinggang hitam", order: 2 },
      { id: "al1-3", label: "Pasang dasi abu-abu di kerah leher dan kencangkan", order: 3 },
      { id: "al1-4", label: "Pakai kaos kaki putih setinggi betis dan sepatu hitam bertali", order: 4 },
      { id: "al1-5", label: "Pakai topi upacara dan periksa kerapian di cermin", order: 5 },
    ],
    targetSequence: ["al1-1", "al1-2", "al1-3", "al1-4", "al1-5"],
    hint: "Pakaian dalam/utama dulu -> celana & ikat pinggang -> aksesori leher -> kaos kaki & sepatu -> topi di kepala.",
    ctExplanation: "Algoritma sekuensial (runtut) mengharuskan prasyarat (pre-condition) terpenuhi sebelum langkah berikutnya dapat dieksekusi.",
    dailyLifeBenefit: "Berpakaian selesai dalam 3 menit tanpa ada atribut yang terbalik atau tertinggal di kamar."
  },
  {
    id: "alg-2",
    pillar: "algoritma",
    pillarNumber: 2,
    title: "Langkah Menyeduh Teh Hangat Manis di Kantin",
    subtitle: "Pilar Algoritma • Urutan proses pelarutan gula dan ekstraksi teh",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Ibu kantin mengajarkan cara menyeduh teh manis yang harum dan gulanya larut sempurna tanpa butiran tersisa di dasar gelas.",
    studentChallenge: "Susun algoritma menyeduh teh manis hangat langkah demi langkah!",
    instruction: "Urutkan proses persiapan hingga siap disajikan.",
    gameType: "sequence",
    items: [
      { id: "al2-1", label: "Masukkan 1 kantung teh celup ke dalam gelas kosong", order: 1 },
      { id: "al2-2", label: "Tuangkan air panas mendidih hingga 3/4 tinggi gelas", order: 2 },
      { id: "al2-3", label: "Celup-celupkan kantung teh selama 2-3 menit hingga air berwarna kemerahan", order: 3 },
      { id: "al2-4", label: "Angkat kantung teh, lalu masukkan 2 sendok teh gula pasir", order: 4 },
      { id: "al2-5", label: "Aduk memutar searah jarum jam hingga gula larut sempurna dan sajikan hangat", order: 5 },
    ],
    targetSequence: ["al2-1", "al2-2", "al2-3", "al2-4", "al2-5"],
    hint: "Air panas melarutkan teh dulu -> buang kantong teh -> masukkan gula -> aduk rata.",
    ctExplanation: "Jika gula dimasukkan sebelum teh diekstraksi, kekentalan larutan akan menghambat ekstraksi warna teh.",
    dailyLifeBenefit: "Minuman teh memiliki rasa manis dan aroma pekat yang konsisten setiap kali dibuat."
  },
  {
    id: "alg-3",
    pillar: "algoritma",
    pillarNumber: 3,
    title: "Prosedur Meminjam Buku di Perpustakaan Sekolah",
    subtitle: "Pilar Algoritma • Alur transaksi peminjaman buku perpustakaan",
    difficulty: "pemula",
    difficultyBadge: "Mudah / Pemula",
    storyContext: "Perpustakaan SMA memiliki tata tertib baku peminjaman buku untuk mencegah buku hilang atau tertukar.",
    studentChallenge: "Urutkan alur peminjaman buku dari siswa tiba sampai membawa buku pulang!",
    instruction: "Susun tahapan operasional perpustakaan secara kronologis.",
    gameType: "sequence",
    items: [
      { id: "al3-1", label: "Isi buku tamu pengunjung di komputer resepsionis depan", order: 1 },
      { id: "al3-2", label: "Cari buku di rak sesuai kode klasifikasi DDC / katalog OPAC", order: 2 },
      { id: "al3-3", label: "Bawa buku dan Kartu Pelajar ke meja petugas sirkulasi", order: 3 },
      { id: "al3-4", label: "Petugas memindai barcode buku dan merekam tanggal pengembalian", order: 4 },
      { id: "al3-5", label: "Terima stempel batas waktu di slip buku dan simpan buku dengan aman", order: 5 },
    ],
    targetSequence: ["al3-1", "al3-2", "al3-3", "al3-4", "al3-5"],
    hint: "Presensi masuk -> cari barang -> ke kasir/petugas -> scan data -> terima bukti pinjam.",
    ctExplanation: "Ini adalah Business Process Modeling (BPM) yang menggambarkan siklus transaksi aman tanpa kebocoran aset.",
    dailyLifeBenefit: "Proses pinjam buku cepat hanya 1 menit dan tidak terkena teguran petugas perpustakaan."
  },
  {
    id: "alg-4",
    pillar: "algoritma",
    pillarNumber: 4,
    title: "Binary Search: Mencari Kamus di Rak 100 Buku",
    subtitle: "Pilar Algoritma • Algoritma Pencarian Biner (Divide and Conquer)",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Rak buku perpustakaan memuat 100 kamus yang sudah terurut rapi dari nomor 1 sampai 100. Kamu mencari 'Kamus No. 73'. Jika mengecek satu per satu (Linear Search), butuh hingga 73 langkah!",
    studentChallenge: "Dengan Algoritma Binary Search, kita selalu memeriksa BUKU TENGAH dari rentang aktif. Berapa langkah pencarian maksimal yang dibutuhkan untuk menemukan buku No. 73?",
    instruction: "Hitung pembagian rentang: (1-100 -> tengah 50 -> 51-100 -> tengah 75 -> 51-74 ...)",
    gameType: "pattern_detect",
    items: [
      { id: "al4-opt1", label: "73 Langkah (Cek satu per satu)", isCorrect: false },
      { id: "al4-opt2", label: "Hanya 6 sampai 7 Langkah!", isCorrect: true, details: "Karena rentang selalu dibagi 2 setiap langkah: 100 -> 50 -> 25 -> 12 -> 6 -> 3 -> 1. Kompleksitas log2(100) ≈ 7 langkah! Jauh lebih efisien dari 73 langkah." },
      { id: "al4-opt3", label: "50 Langkah", isCorrect: false },
      { id: "al4-opt4", label: "100 Langkah", isCorrect: false },
    ],
    hint: "Binary search membelah dua rentang pencarian setiap kali menebak.",
    ctExplanation: "Algoritma Pencarian Biner (Binary Search) memiliki kompleksitas waktu O(log N), merupakan kunci kecepatan database Google dan mesin pencari modern.",
    dailyLifeBenefit: "Menemukan buku apa pun di perpustakaan dalam hitungan detik tanpa membuka rak dari ujung ke ujung."
  },
  {
    id: "alg-5",
    pillar: "algoritma",
    pillarNumber: 5,
    title: "Bubble Sort: Mengurutkan Barisan Upacara Sesuai Tinggi Badan",
    subtitle: "Pilar Algoritma • Mengurutkan siswa dari paling pendek ke paling tinggi",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Pemimpin barisan ingin 5 siswa (Tinggi: 172cm, 160cm, 168cm, 155cm, 180cm) berbaris rapi dari terpendek ke tertinggi agar barisan upacara terlihat kompak.",
    studentChallenge: "Bagaimana cara kerja 1 langkah perbandingan dasar pada algoritma Bubble Sort?",
    instruction: "Pilih prinsip pertukaran (swap) pada Bubble Sort.",
    gameType: "pattern_detect",
    items: [
      { id: "al5-opt1", label: "Acak posisi siswa secara acak sampai pas", isCorrect: false },
      { id: "al5-opt2", label: "Bandingkan dua siswa yang berdiri berdampingan; jika siswa sebelah kiri lebih tinggi dari sebelah kanan, tukar posisi mereka", isCorrect: true, details: "Bubble sort memeriksa pasangan bersebelahan secara berulang, mendorong angka yang lebih besar ke arah kanan secara bertahap seperti gelembung air." },
      { id: "al5-opt3", label: "Keluarkan semua siswa dari barisan dan suruh lari keliling lapangan", isCorrect: false },
      { id: "al5-opt4", label: "Pilih siswa paling berat untuk berdiri di tengah", isCorrect: false },
    ],
    hint: "Bandingkan tetangga sebelah: jika kiri > kanan, tukar tempat.",
    ctExplanation: "Algoritma Pengurutan (Sorting) adalah pilar fundamental ilmu komputer untuk menyusun data agar mudah diindeks dan dicari.",
    dailyLifeBenefit: "Barisan kelas di lapangan langsung rapi simetris dalam 1 menit tanpa saling dorong."
  },
  {
    id: "alg-6",
    pillar: "algoritma",
    pillarNumber: 6,
    title: "Prosedur Surat Izin Meninggalkan Kelas ke Ruang UKS",
    subtitle: "Pilar Algoritma • Percabangan kondisi (If-Else) perizinan sekolah",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Siswa yang merasa pusing di tengah jam pelajaran harus mengikuti prosedur SOP sekolah agar tidak dianggap membolos.",
    studentChallenge: "Urutkan langkah perizinan resmi dari izin guru pengajar hingga istirahat di UKS!",
    instruction: "Susun alur penanganan siswa sakit sesuai tata tertib.",
    gameType: "sequence",
    items: [
      { id: "al6-1", label: "Angkat tangan dan sampaikan kondisi kesehatan ke Guru yang mengajar di kelas", order: 1 },
      { id: "al6-2", label: "Terima surat pengantar izin keluar kelas berwarna kuning dari meja guru", order: 2 },
      { id: "al6-3", label: "Berjalan menuju ruang UKS didampingi satu orang teman sekelas", order: 3 },
      { id: "al6-4", label: "Petugas PMR / Pembina UKS memeriksa suhu tubuh dan mencatat di buku medis", order: 4 },
      { id: "al6-5", label: "Jika suhu > 38°C hubungi orang tua untuk dijemput; Jika pusing ringan istirahat 30 menit dan minum teh hangat", order: 5 },
    ],
    targetSequence: ["al6-1", "al6-2", "al6-3", "al6-4", "al6-5"],
    hint: "Izin guru kelas -> bawa surat pengantar -> ke UKS bersama teman -> diperiksa PMR -> keputusan tindak lanjut.",
    ctExplanation: "Algoritma dengan struktur kontrol percabangan (Condition/Branching) mengarahkan tindakan berbeda berdasarkan hasil observasi parameter kesehatan.",
    dailyLifeBenefit: "Mendapatkan penanganan medis cepat dan terbebas dari catatan pelanggaran membolos jam sekolah."
  },
  {
    id: "alg-7",
    pillar: "algoritma",
    pillarNumber: 7,
    title: "Algoritma Greedy: Pecahan Uang Kembalian Koperasi",
    subtitle: "Pilar Algoritma • Memberikan kembalian dengan lembar uang paling sedikit",
    difficulty: "menengah",
    difficultyBadge: "Sedang / Menengah",
    storyContext: "Seorang siswa belanja buku seharga Rp 32.000 dan membayar dengan uang Rp 50.000. Uang kembalian yang harus diberikan kasir koperasi adalah Rp 18.000. Kasir memiliki pecahan Rp 10.000, Rp 5.000, Rp 2.000, dan Rp 1.000.",
    studentChallenge: "Dengan Algoritma Greedy (mengambil pecahan terbesar yang memungkinkan terlebih dahulu), kombinasi uang kembalian manakah yang paling efisien (jumlah lembar paling sedikit)?",
    instruction: "Cari kombinasi pecahan uang paling sedikit untuk total Rp 18.000.",
    gameType: "pattern_detect",
    items: [
      { id: "al7-opt1", label: "18 lembar uang Rp 1.000 (Sangat boros kertas)", isCorrect: false },
      { id: "al7-opt2", label: "9 lembar uang Rp 2.000", isCorrect: false },
      { id: "al7-opt3", label: "1 lembar Rp 10.000 + 1 lembar Rp 5.000 + 1 lembar Rp 2.000 + 1 lembar Rp 1.000 (Total 4 Lembar)", isCorrect: true, details: "Algoritma Greedy memilih pecahan terbesar yang muat: 10.000 (sisa 8.000) -> 5.000 (sisa 3.000) -> 2.000 (sisa 1.000) -> 1.000 (sisa 0). Total hanya 4 lembar!" },
      { id: "al7-opt4", label: "3 lembar Rp 5.000 + 3 lembar Rp 1.000 (Total 6 Lembar)", isCorrect: false },
    ],
    hint: "Ambil pecahan terbesar dulu (10 ribu), lalu pecahan terbesar berikutnya yang cukup.",
    ctExplanation: "Greedy Algorithm selalu membuat pilihan lokal optimal pada setiap langkah dengan harapan menemukan solusi global optimal.",
    dailyLifeBenefit: "Dompet pembeli tidak tebal oleh uang receh dan antrean kasir koperasi berjalan cepat."
  },
  {
    id: "alg-8",
    pillar: "algoritma",
    pillarNumber: 8,
    title: "Algoritma Dijkstra: Rute Tercepat Pulang Sekolah Menghindari Macet",
    subtitle: "Pilar Algoritma • Menghitung bobot waktu tersingkat di setiap persimpangan jalan",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Dari gerbang sekolah menuju rumahmu ada 3 jalur alternatif: Jalur A (Jalan Raya Protokol: Jarak 4 km, tapi macet lampu merah, waktu tempuh 25 menit). Jalur B (Jalan Lingkar Luar: Jarak 8 km, lancar bebas hambatan, waktu tempuh 14 menit). Jalur C (Gang Pemukiman: Jarak 3 km, sempit banyak polisi tidur, waktu tempuh 18 menit).",
    studentChallenge: "Jika tujuanmu adalah TIBA DI RUMAH PALING CEPAT (Shortest Time Path), jalur manakah yang dipilih algoritma navigasi GPS?",
    instruction: "Pilih jalur dengan bobot total waktu tersingkat, bukan sekadar jarak fisik.",
    gameType: "pattern_detect",
    items: [
      { id: "al8-opt1", label: "Jalur A (25 Menit) - Karena jalan raya utama", isCorrect: false },
      { id: "al8-opt2", label: "Jalur B (14 Menit) - Waktu tempuh tercepat meski jarak fisik lebih panjang", isCorrect: true, details: "Algoritma Dijkstra meminimalkan fungsi biaya (cost function) berupa waktu menit. Jalur B menghemat 11 menit dibanding Jalur A." },
      { id: "al8-opt3", label: "Jalur C (18 Menit) - Karena jarak kilometer paling pendek", isCorrect: false },
      { id: "al8-opt4", label: "Berputar-putar di sekolah sampai malam", isCorrect: false },
    ],
    hint: "Fokus pada angka menit waktu tempuh terkecil.",
    ctExplanation: "Algoritma Jalur Terpendek Dijkstra memperhitungkan bobot tepi (edge weight) yang dinamis, bukan hanya geometri peta statis.",
    dailyLifeBenefit: "Sampai di rumah 11 menit lebih awal untuk istirahat dan mempersiapkan tugas hari berikutnya."
  },
  {
    id: "alg-9",
    pillar: "algoritma",
    pillarNumber: 9,
    title: "Algoritma Tabulasi Suara Pemilihan Ketua OSIS",
    subtitle: "Pilar Algoritma • Penghitungan suara cepat (Quick Count) dengan validasi suara sah",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Panitia Komisi Pemilihan OSIS menghitung 600 surat suara dari 3 kotak suara. Diperlukan algoritma penghitungan yang transparan dan anti-kecurangan.",
    studentChallenge: "Urutkan alur algoritma penghitungan suara di depan saksi kelas!",
    instruction: "Susun alur penghitungan suara demokratis yang sistematis.",
    gameType: "sequence",
    items: [
      { id: "al9-1", label: "Buka gembok kotak suara dan hitung total lembar surat suara di depan saksi", order: 1 },
      { id: "al9-2", label: "Ambil satu lembar surat suara dan periksa keabsahan tanda coblosan (Sah / Tidak Sah)", order: 2 },
      { id: "al9-3", label: "Bacakan nama kandidat yang tercoblos dengan lantang ke seluruh hadirin", order: 3 },
      { id: "al9-4", label: "Tuliskan 1 garis tally (I) di papan plano hitung suara pada kolom kandidat yang bersangkutan", order: 4 },
      { id: "al9-5", label: "Ulangi langkah 2 s.d 4 hingga surat suara habis, lalu jumlahkan total suara dan buat berita acara", order: 5 },
    ],
    targetSequence: ["al9-1", "al9-2", "al9-3", "al9-4", "al9-5"],
    hint: "Buka kotak -> validasi lembar -> sebutkan pilihan -> tambah tally papan -> loop hingga selesai.",
    ctExplanation: "Ini adalah algoritma perulangan (Loop / While Not End of File) dengan akumulator data (counter/tally).",
    dailyLifeBenefit: "Hasil pemilu OSIS dipercaya 100% oleh seluruh warga sekolah tanpa ada sengketa atau tuduhan curang."
  },
  {
    id: "alg-10",
    pillar: "algoritma",
    pillarNumber: 10,
    title: "Prosedur Backup Otomatis File Tugas ke Google Drive",
    subtitle: "Pilar Algoritma • Siklus sinkronisasi data aman (Check, Compress, Sync, Verify)",
    difficulty: "mahir",
    difficultyBadge: "Sulit / Mahir",
    storyContext: "Laptop sering kali mendadak rusak atau terkena virus sebelum pengumpulan tugas makalah akhir semester. Siswa membutuhkan skrip algoritma pencadangan otomatis.",
    studentChallenge: "Urutkan algoritma sistem pencadangan (backup) file tugas sekolah yang paling aman!",
    instruction: "Susun prosedur siklus backup data integritas tinggi.",
    gameType: "sequence",
    items: [
      { id: "al10-1", label: "Pindai folder tugas sekolah untuk mencari file yang baru diubah hari ini (Modified Date)", order: 1 },
      { id: "al10-2", label: "Kompres file-file tersebut ke dalam satu arsip terenkripsi ZIP", order: 2 },
      { id: "al10-3", label: "Hubungkan koneksi aman HTTPS ke cloud Google Drive dengan token autentikasi", order: 3 },
      { id: "al10-4", label: "Unggah arsip ZIP ke folder cadangan awan (Upload Stream)", order: 4 },
      { id: "al10-5", label: "Verifikasi kecocokan ukuran file (Checksum/Hash) dan tampilkan notifikasi 'Backup Sukses'", order: 5 },
    ],
    targetSequence: ["al10-1", "al10-2", "al10-3", "al10-4", "al10-5"],
    hint: "Cari file baru -> bungkus zip -> koneksi ke cloud -> unggah -> cek hash keutuhan file.",
    ctExplanation: "Algoritma backup industri menggunakan incremental scan dan SHA-256 hash checksum untuk menjamin data integrity.",
    dailyLifeBenefit: "File tugas sekolah tidak pernah hilang selamanya meskipun laptop jatuh atau terhapus secara tidak sengaja."
  }
];
